FactoryBot.create :user, email: "joe@test.com", password: "test123", password_confirmation: "test123"
FactoryBot.create :user, :admin, email: "admin@test.com", password: "test123", password_confirmation: "test123"
FactoryBot.create :episode, published_on: 1.day.ago, file_url: "test1.mp3", slug: "003-soli"
FactoryBot.create :episode, title: "Reiter", published_on: 7.days.ago, file_url: "test2.mp3", slug: "002-reiter"
FactoryBot.create :episode, title: "Grüne", published_on: 1.month.ago, file_url: "test3.mp3", slug: "001-grune"
